#!/bin/bash
# ansi.sh from: https://gist.github.com/jaggzh/6b3746475bbde5a077dfaeae793b7d1f
. ansi.sh
# fn.readcountdown from: https://gist.github.com/jaggzh/a66f35114ac0c0b3201f43ec09b10f22
. fn.readcountdown

# echo "$@"
# exit

# We're using:
# highlight -S "$syntax" \
# 	--style neon \
# 	-O truecolor >&2

# highlight --styles
#   Lang prefs:
#     python candidates
#       andes blacknblue bluegreen candy dusk freya kellys
#		lucretia molokai moria navy neon
themes_hi_python=(
       andes blacknblue bluegreen candy dusk freya
		kellys lucretia molokai moria navy neon
)
themes_hi_python=(
       dusk neon
)
hi_theme=neon

get_themes_hi () {
	hi_theme_dir=/usr/share/highlight/themes
	cd -- "$hi_theme_dir"
	ls *.theme | sed -e 's/\.theme$//'
}


opt_eval=
theme_preview=1
theme_preview=
nocopy=

usage () {
	cat <<"EOT"
This is used to make a runnable script that's a displayable document.
  * Displays current script body on the screen
  * Has a countdown timer to copy the script body to the clipboard (default)
  * Allows language selecting and does syntax highlighting

Generally, just use this she-bang to make the script into a document:
  #!/usr/bin/env -S display_file_shell
or, for example, for perl:
  #!/usr/bin/env -S display_file_shell -l perl

More info:
When used as a script's shell, display_file_shell will display the CONTENTS of
the current script, with syntax highlighting, and allow it to be copied to the
clipboard automatically.

(Shells generally aren't callable with the she-bang (#! without
being added to the system, so for end-user use you most likely
want to use the /usr/bin/env she-bang line above)

Options to display_file_shell:
    -l) syntax         Language
    -c) highlight_cmd  Override (not implemented)
    -t) timeout        Prompt for copy-to-clibpard (def 30)
    -e) eval           Eval doc str to expand vars (not implemented)
    -T) pretend terminal  Piping:
                           disables color,
                           asking to copy to clipboard,
                           and the stderr duplication of the output
                          This allows them again.
    -C) nocopy         Don't prompt or copy to clipboard
    -s) syncol         Set to anything to use gnu syntax-highlight
    -h) help
    -T) theme preview  Show all themes (for `highlight` only)
    -v) verbose        No you shhh.
EOT
}
opt_terminal=0
opt_do_highlighting=1

display_file() {
	local timeout=30 syntax filename syncol verbose highlight_cmd

	while getopts "c:l:t:TCs:hEv" opt; do
		case ${opt} in
			c) highlight_cmd="${OPTARG}" ;;
			l) syntax="${OPTARG}" ;;
			t) timeout="${OPTARG}" ;;
			e) opt_eval="${OPTARG}" ;;
			T) opt_terminal="${OPTARG}" ;;
			C) nocopy=1 ;;
			s) syncol=1 ;;
			h) help=1 ;;
			T) themepreview=1 ;;
			v) verbose=1 ;;
			\?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
			:) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
		esac
	done
	shift $((OPTIND -1))
	if [[ -n $help ]]; then usage; exit; fi

	if [[ ! -t 1 ]]; then # stdout not a terminal
		if [[ "$opt_terminal" = 0 ]]; then # Standard behavior for piping: Disable copy and highlighting
			nocopy=1
			opt_do_highlighting=0
		fi
	fi


	# If -l is not present, read the second line of the file (assuming it's the shebang)
	# echo "Syntax: {$syntax}"
	filename="$1"
	# echo "Filename: {$filename}"

		##################################################
		## Syntax coming from -l option
	if [[ -n "$syntax" ]]; then
		case "$syntax" in
			*python*) syntax="python" ;;
		esac
	else
		##################################################
		## No syntax, so try to determine from shebang
		[[ -n $verbose ]] && {
			echo -n "Running sed: "
			sed -n '2p' "$filename"
		}
		[[ -n $verbose ]] && echo "Done. Getting shebang from line 2..."
		read -r shebang < <(sed -n '2p' "$filename")
		[[ -n $verbose ]] && echo "Shebang: {$shebang}"
		# Parse out the language from the shebang
		case "$shebang" in
			*bin/bash*) syntax="bash" ;;
			*python*) syntax="python" ;;
			*bin/perl*) syntax="perl" ;;
			*)	echo "Unknown shebang. Setting blank syntax." >&2
				syntax=""
				;;
		esac
		[[ -n $verbose ]] && echo "Syntax chosen: $syntax"
	fi

	# Save file content into a variable
	local content=$(tail -n +2 "$filename")

	# Highlight and display the file (excluding the first two lines)
	if [[ "$opt_do_highlighting" = 0 ]]; then
		printf '%s' "$content"
	elif [[ $syntax = '' ]]; then
		printf '%s' "$content" >&2
	else
		if [[ -z syncol ]];  then
			#printf '%s' "$content" | source-highlight -f esc256 -o STDOUT -O truecolor -s "$syntax" --style-file esc256.style >&2
			high_cmd=(source-highlight -f esc256 -o STDOUT -s "$syntax" --style-file esc256.style)
			[[ -n $verbose ]] && echo "Highlight command: {${high_cmd[@]}}"
			printf '%s' "$content" | "${high_cmd[@]}" >&2
		else
			theme=$hi_theme
			if [[ -z $theme_preview ]]; then
				high_cmd=(highlight -S "$syntax"
						--style "$theme"
						-O truecolor)
				[[ -n $verbose ]] && echo "Highlight command: {${high_cmd[@]}}"
				printf '%s' "$content" | "${high_cmd[@]}" >&2
			else
				themes=(${themes_hi_python[@]})
				# themes=($(get_themes_hi))
				for theme in "${themes[@]}"; do
					echo "$bgblu${yel} ==== Theme: $theme  $rst"
					high_cmd=(highlight -S "$syntax"
							--style "$theme"
							-O truecolor)
					[[ -n $verbose ]] && echo "Highlight command: {${high_cmd[@]}}"
					printf '%s' "$content" | "${high_cmd[@]}" >&2
				done
			fi
		fi
	fi
	echo

	if [[ "$nocopy" != 1 ]]; then
		readcountdown1 "$timeout" ans "$bgblu${yel} Copy to clipboard? (${timeout}s) $rst (Y/${bcya}n$rst) "
		[[ $ans = '' || $ans = y* || $ans = Y* ]] && printf '%s' "$content" | xc && echo "Copied to clipboard" >&2
	fi
}

display_file "$@"
